### PR TITLE
Fix #1556 and #1557

### LINKED ISSUE #1525: Allow PropertySpec with context receivers and without getter or setter
Such code is valid in kotlin but fails to be generated by kotlinpoet with the error: `properties with context receivers require a getter`:

```kotlin
interface Bar {
   context(LoggingScope)
   val foo: Int
}
```

### LINKED ISSUE #1556: TypeSpec for Kotlin object can emit abstract functions
**Describe the bug**
The current validation logic in `TypeSpec.kt` does not prevent emitting the following code:

```kotlin
object Foo {
    abstract fun bar()
}
```

**To Reproduce**

Failing test:

```kotlin
  @Test fun abstractFunForbiddenInObject() {
    val type = TypeSpec.objectBuilder("Taco")

    assertThrows<IllegalArgumentException> {
      type.addFunction(
        FunSpec.builder("eat")
          .addModifiers(ABSTRACT)
          .build(),
      )
        .build()
    }.hasMessageThat().isEqualTo("non-abstract type Taco cannot declare abstract function eat")
  }
```

**Expected behavior**
An exception similar to when we add an abstract function to a non-abstract class.

**Additional context**
I'm trying to fix #1525 which would involve moving validation logic from inside `PropertySpec.kt` into `TypeSpec.kt`. When I was doing this, I noticed some of the other logic in `TypeSpec.kt` has drifted.

### LINKED ISSUE #1557: TypeSpec for annotation can emit member functions and secondary constructors
**Describe the bug**
The current validation logic in `TypeSpec.kt` does not prevent emitting the following code:

```kotlin
public annotation class Taco() {
  public constructor(`value`: kotlin.String)
}
```

```kotlin
public annotation class Taco() {
  public fun eat(`value`: kotlin.String): kotlin.Unit
}
```

**To Reproduce**

Generates secondary constructor:
```kotlin
    TypeSpec.annotationBuilder("Taco")
      .primaryConstructor(
        FunSpec.constructorBuilder()
          .build(),
      )
      .addFunction(
        FunSpec.constructorBuilder()
          .addParameter("value", String::class)
          .addModifiers(PUBLIC, ABSTRACT)
          .build(),
        )
      .build()
```

Generates member function:
```kotlin
    TypeSpec.annotationBuilder("Taco")
      .primaryConstructor(
        FunSpec.constructorBuilder()
          .build(),
      )
      .addFunction(
        FunSpec.builder("eat")
          .addParameter("value", String::class)
          .addModifiers(PUBLIC, ABSTRACT)
          .build(),
        )
      .build()
```   

**Expected behavior**
Exceptions with a message like "annotation class Taco cannot declare member function eat"

**Additional context**
I'm trying to fix #1525 which would involve moving validation logic from inside `PropertySpec.kt` into `TypeSpec.kt`. When I was doing this, I noticed some of the other logic in `TypeSpec.kt` has drifted.

### PR DESCRIPTION
**Pull request by drawers**
Got bored at work so decided to look at `TypeSpec.kt` for #1556 and #1557 with the aim to eventually solve #1525

See also this comment:
https://github.com/square/kotlinpoet/issues/1556#issuecomment-1557620954

Closes #1556. Closes #1557.

### CODE REVIEW

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 1]
```diff
@@ -771,8 +770,7 @@ public class TypeSpec private constructor(
         "typevariables are forbidden on anonymous types"
       }
 
-      val isAbstract = ABSTRACT in modifiers || SEALED in modifiers || kind != Kind.CLASS ||
```
Comment (drawers) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt:774]: `kind != Kind.CLASS` is the condition that is allowing objects to have abstract functions

**Review by JakeWharton — APPROVED** [review]
