### PR TITLE
Fix Class not calling through to superclass constructor when superclass has a no-arg constructor.

### LINKED ISSUE #120: Class not calling through to superclass constructor when superclass has a no-arg constructor
`val typeBuilder = TypeSpec.classBuilder("Foo").superclass(Bar::class)`

This generates `class Foo : Bar`, which does not compile in Kotlin 1.1.2. I read through the documentation and the TypeSpecTests to try to get some insight, but I found nothing that indicates that I'm omitting a function call that adds the superclass constructor call.

### PR DESCRIPTION
**Pull request by vanniktech**
Fixes #120

### CODE REVIEW

File: src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 1]
```diff
@@ -113,6 +113,7 @@ class TypeSpec private constructor(builder: TypeSpec.Builder) {
 
         val extendsTypes: List<TypeName>
         val implementsTypes: List<TypeName>
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: Is the distinction between these necessary? Seems like a carryover from JavaPoet that has no place here.

File: src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 2]
```diff
@@ -111,20 +111,20 @@ class TypeSpec private constructor(builder: TypeSpec.Builder) {
           codeWriter.emit(")")
         }
 
-        val extendsTypes: List<TypeName>
-        val implementsTypes: List<TypeName>
+        val superTypes: List<Pair<TypeName, String>>
+
         if (kind == Kind.INTERFACE) {
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: This whole conditional can be dropped now

File: src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 3]
```diff
@@ -111,20 +111,20 @@ class TypeSpec private constructor(builder: TypeSpec.Builder) {
           codeWriter.emit(")")
         }
 
-        val extendsTypes: List<TypeName>
-        val implementsTypes: List<TypeName>
+        val superTypes: List<Pair<TypeName, String>>
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: Maybe consider `List<CodeBlock>` and do `CodeBlock.of("%T", type)` or `CodeBlock.of("%T()", type)`.
