### PR TITLE
Emit initializers in order with properties

### LINKED ISSUE #800: Order matters for class initializers, but kotlinpoet always emits them after properties
Consider the following class

```kotlin
class Taco(vararg seasonings: String) {
  private val firstSeasoning = seasonings[0]
  init {
    require(seasonings.isNotEmpty()) {
      "Seasonings cannot be empty!"
    }
  }
}

class TacoTest {
  @Test fun runTest() {
    Taco()
  }
}
```

This would throw an `IndexOutOfBoundsException` because `firstSeasoning` is initialized first

Now if we change the class

```kotlin
class Taco(vararg seasonings: String) {
  init {
    require(seasonings.isNotEmpty()) {
      "Seasonings cannot be empty!"
    }
  }
  private val firstSeasoning = seasonings[0]
}
```

Now the test would throw an `IllegalArgumentException` from the `require()` call

### PR DESCRIPTION
**Pull request by ZacSweers**
This change adds tracking for initializer blocks to know what property index it should be emitted with respect to.

Resolves #800

### CODE REVIEW

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 1]
```diff
@@ -419,6 +443,7 @@ class TypeSpec private constructor(
     internal var primaryConstructor: FunSpec? = null
     internal var superclass: TypeName = ANY
     internal val initializerBlock = CodeBlock.builder()
+    var initializerIndex = -1
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: Should be `internal`

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 2]
```diff
@@ -291,8 +305,16 @@ class TypeSpec private constructor(
   private fun constructorProperties(): Map<String, PropertySpec> {
     if (primaryConstructor == null) return emptyMap()
 
+    // Properties added after the initializer are not permitted to be inlined into the constructor
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: Something that we can improve in future?

Comment (ZacSweers) [reply kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: Nope it's not allowed in kotlin

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt (hunk 1 above)
Comment (ZacSweers) [reply kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: I kept it public because someone calling `toBuilder()` could want to change this order
