### PR TITLE
Fix trailing newline in PropertySpec

### LINKED ISSUE #941: Consecutive blank lines with top level property
I'm noticing that when creating a top-level property in a file, two blank lines are output below the property, causing detekt to fail with a `NoConsecutiveBlankLines` violation.

Sample `FileSpec`:
```
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.PropertySpec

val spec = FileSpec.builder("com.example.foo", "Test")
  .addProperty(
    PropertySpec.builder("MyProperty", String::class.java)
      .initializer(
        CodeBlock.builder()
            .beginControlFlow("if (1 + 1 == 2)")
            .addStatement("Expected")
            .endControlFlow()
            .beginControlFlow("else")
            .addStatement("Unexpected")
            .endControlFlow()
            .build()
      ).build()
  ).build()
```

Results in:
```
val equals = """
    |package com.example.foo
    |
    |import java.lang.String
    |
    |val MyProperty: String = if (1 + 1 == 2) {
    |  Expected
    |}
    |else {
    |  Unexpected
    |}
    |
    | <-- Extra line. Removing this causes `equals` to be `false`
""".trimMargin() == spec.toString()
println(equals) <-- Prints `true`
```

I don't think we should ever have consecutive blank lines.

### PR DESCRIPTION
**Pull request by psymoon**
This happens because things like `.endControlFlow` adds `\n`. This removes any trailing newline before emitting the `initializer`.

Closes #941

- [x] `docs/changelog.md` has been updated if applicable.

### CODE REVIEW

File: kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/Util.kt [hunk 1]
```diff
@@ -138,19 +138,28 @@ internal fun stringLiteralWithQuotes(
   }
 }
 
-internal fun CodeBlock.ensureEndsWithNewLine() = if (isEmpty()) {
+internal fun CodeBlock.ensureEndsWithNewLine() = trimTrailingNewLine('\n')
+
+internal fun CodeBlock.trimTrailingNewLine(replaceWith: Char? = null) = if (isEmpty()) {
```
Comment (Egorand) [inline kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/Util.kt:143]: I really like this!

**Review by Egorand — APPROVED** [review]
Very nice!
