### PR TITLE
Fix abstract element handling

### LINKED ISSUE #820: Metadata: IllegalArgumentException: abstract function get() cannot have code --  caused by internal abstract property
```kotlin
 @Test
  fun internalAbstractProperty() {
    val typeSpec = InternalAbstractPropertyHolder::class.toTypeSpec()
  }

  abstract class InternalAbstractPropertyHolder {
    internal abstract val test2: String
  }
```
leads to following stacktrace: current state of master
```
java.lang.IllegalArgumentException: abstract function get() cannot have code

	at com.squareup.kotlinpoet.FunSpec.<init>(FunSpec.kt:55)
	at com.squareup.kotlinpoet.FunSpec.<init>(FunSpec.kt:37)
	at com.squareup.kotlinpoet.FunSpec$Builder.build(FunSpec.kt:486)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.propertyAccessor(KotlinPoetMetadataSpecs.kt:715)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toPropertySpec(KotlinPoetMetadataSpecs.kt:680)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:376)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:173)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:138)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:132)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec$default(KotlinPoetMetadataSpecs.kt:131)
```

### LINKED ISSUE #821: Metadata abstract class not working
looking into #820 I noticed that abstract classes in general don't seem to work at all.
Abstract functions just get treated as normal functions.
Abstract properties fail as described in #820 + they seem to generate an initilizer (which is forbidden) if #820 is fixed as in https://github.com/Wasabi375/kotlinpoet/commit/b86c838253e21be4a09ff7567abe90d64835ff8d ([KotlinPoetMetadataSpecs.kt#L675-L687](https://github.com/Wasabi375/kotlinpoet/blob/b86c838253e21be4a09ff7567abe90d64835ff8d/kotlinpoet-metadata-specs/src/main/kotlin/com/squareup/kotlinpoet/metadata/specs/KotlinPoetMetadataSpecs.kt#L675-L687))
```kotlin
        // Delegated properties have setters/getters defined for some reason, ignore here
        // since the delegate handles it
        // vals with initialized constants have a getter in bytecode but not a body in kotlin source
        if(!isAbstract) {  //  ******* this line is new  ******* 
          val modifierSet = modifiers.toSet()
          if (hasGetter && !isDelegated) {
              propertyAccessor(modifierSet, getterFlags,
                      FunSpec.getterBuilder().addStatement(NOT_IMPLEMENTED), isOverride)?.let(::getter)
          }
          if (hasSetter && !isDelegated) {
              propertyAccessor(modifierSet, setterFlags, FunSpec.setterBuilder(), isOverride)?.let(::setter)
          }
        }
```

test for abstract class is here: https://github.com/Wasabi375/kotlinpoet/commit/b73903b6b657b194aa301493fd4046a0f5ee32cf
```kotlin
@Test
  fun abstractClass() {
    val typeSpec = AbstractClass::class.toTypeSpecWithTestHandler()

    //language=kotlin
    assertThat(typeSpec.trimmedToString()).isEqualTo("""
      abstract class AbstractClass {
        val baz: kotlin.String = throw NotImplementedError("Stub!")
        
        abstract val foo: kotlin.String

        abstract fun bar()
        
        fun fuz() {
        } 
      }
    """.trimIndent())
  }

  abstract class AbstractClass {
    abstract val foo: String
    abstract fun bar()

    val baz: String = ""
    fun fuz() {}
  }
```
output:
```
expected:
    abstract class AbstractClass {
      val baz: kotlin.String = = throw NotImplementedError("Stub!")
      
      abstract val foo: kotlin.String
    
      abstract fun bar()
      
      fun fuz() {
      } 
    }
but was:
    abstract class AbstractClass {
      val baz: kotlin.String = throw NotImplementedError("Stub!")
    
      abstract val foo: kotlin.String = throw NotImplementedError("Stub!")
    
      fun bar() {
      }
    
      fun fuz() {
      }
    }
```

### PR DESCRIPTION
**Pull request by ZacSweers**
Fixes #821 
Fixes #820 

This revealed that we're not currently detecting if kotlin interface properties have default values currently, but will save addressing that for another PR

### CODE REVIEW

File: kotlinpoet-metadata-specs-tests/src/test/kotlin/com/squareup/kotlinpoet/metadata/specs/test/KotlinPoetMetadataSpecsTest.kt [hunk 1]
```diff
@@ -1770,6 +1770,137 @@ class KotlinPoetMetadataSpecsTest : MultiClassInspectorTest() {
...
+    """.trimIndent())
+  }
+
+  abstract class InternalAbstractPropertyHolder {
+    internal abstract val valProp: String
+    internal abstract var varProp: String
+  }
+
+  @Test
+  fun modalities() {
```
Comment (ZacSweers) [inline kotlinpoet-metadata-specs-tests/src/test/kotlin/com/squareup/kotlinpoet/metadata/specs/test/KotlinPoetMetadataSpecsTest.kt]: Added this opportunistically to beef up tests around this area.

File: kotlinpoet-metadata-specs/src/main/kotlin/com/squareup/kotlinpoet/metadata/specs/KotlinPoetMetadataSpecs.kt [hunk 2]
```diff
@@ -519,12 +523,19 @@ private fun ImmutableKmConstructor.toFunSpec(
...
 ): FunSpec {
   return FunSpec.builder(name)
       .apply {
         addAnnotations(annotations)
         addVisibility { addModifiers(it) }
+        val isOverride = methodData?.isOverride == true
+        addModifiers(flags.modalities
+            .filterNot { it == FINAL && !isOverride } // Final is the default
+            .filterNot { it == OPEN && isOverride } // Overrides are implicitly open
+            .filterNot { it == OPEN && isInInterface } // functions methods are implicitly open
```
Comment (Wasabi375) [inline kotlinpoet-metadata-specs/src/main/kotlin/com/squareup/kotlinpoet/metadata/specs/KotlinPoetMetadataSpecs.kt]:
```suggestion
            .filterNot { it == OPEN && isInInterface } // interface methods are implicitly open
```

Comment (ZacSweers) [reply kotlinpoet-metadata-specs/src/main/kotlin/com/squareup/kotlinpoet/metadata/specs/KotlinPoetMetadataSpecs.kt]: English is hard 😅

File: kotlinpoet-classinspector-elements/src/main/kotlin/com/squareup/kotlinpoet/classinspector/elements/ElementsClassInspector.kt [hunk 3]
```diff
@@ -201,10 +201,10 @@ class ElementsClassInspector private constructor(
     //       and compare against only preceding ones.
     val methodList = methodMap.asMap()[simpleName.toString()]?.toList()
         ?: return false
-    val indexOfPossibleOverrider = methodList.indexOf(this)
-    return (indexOfPossibleOverrider downTo 0)
-        .asSequence()
-        .map { methodList[it] }
+    val signature = jvmMethodSignature(types)
```
Comment (Egorand) [inline kotlinpoet-classinspector-elements/src/main/kotlin/com/squareup/kotlinpoet/classinspector/elements/ElementsClassInspector.kt]: Looks like the comment on line 198 is obsolete after this change. I'd vote for deleting it completely cause it tries to explain the algorithm that isn't complicated enough to warrant a comment.
