### PR TITLE
Fix backward typevariable references in bounds

### LINKED ISSUE #812: Circular Generic Type -- Metadata: java.lang.IllegalStateException: No type argument found for 0!
I tried to reproduce this bug https://github.com/square/moshi/issues/955 directly with kotlinpoet:
By adding this to KotlinPoetMetadataSpecTest
```kotlin
class Asset<A: Asset<A>>
class AssetMetaData<A: Asset<A>>

@Test
fun noTypeArgumentFound() {
  AssetMetaData::class.toTypeSpecWithTestHandler()
}
```
I got the following error
```
java.lang.IllegalStateException: No type argument found for 0!

	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeParamsResolver$typeParamResolver$1.invoke(KotlinPoetMetadataSpecs.kt:198)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs$toTypeParamsResolver$typeParamResolver$1.invoke(KotlinPoetMetadataSpecs.kt)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:84)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName$default(KmTypes.kt:79)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:62)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName(KmTypes.kt:81)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeName$default(KmTypes.kt:79)
	at com.squareup.kotlinpoet.metadata.specs.internal.KmTypesKt.toTypeVariableName(KmTypes.kt:161)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeParamsResolver(KotlinPoetMetadataSpecs.kt:201)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeParamsResolver$default(KotlinPoetMetadataSpecs.kt:192)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:211)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:173)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:138)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec(KotlinPoetMetadataSpecs.kt:132)
	at com.squareup.kotlinpoet.metadata.specs.KotlinPoetMetadataSpecs.toTypeSpec$default(KotlinPoetMetadataSpecs.kt:131)
```
which matches my error in moshi. As far as I can tell this is due to the circular generic type definition.

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves #812

### CODE REVIEW

File: kotlinpoet-metadata-specs/src/main/kotlin/com/squareup/kotlinpoet/metadata/specs/internal/KmTypes.kt [hunk 1]
```diff
@@ -148,14 +148,7 @@ internal fun ImmutableKmType.toTypeName(
...
 ): TypeVariableName {
-  val finalVariance = variance.toKModifier().let {
-    if (it == KModifier.OUT) {
-      // We don't redeclare out variance here
-      null
-    } else {
-      it
-    }
-  }
+  val finalVariance = variance.toKModifier()
```
Comment (ZacSweers) [inline kotlinpoet-metadata-specs/src/main/kotlin/com/squareup/kotlinpoet/metadata/specs/internal/KmTypes.kt]: This was a bug revealed by the regression test I added, opportunistically fixed here. Was a hold-over from Moshi's handling of metadata
