### PR TITLE
Fix annotation syntax when used as params

### LINKED ISSUE #146: Nested annotations shouldn't emit @
```kotlin
@Foo(things = [Bar(), Baz()])
// not
@Foo(things = [@Bar(), @Baz()])
```

### PR DESCRIPTION
**Pull request by Egorand**
Fixes #146 and #147

### CODE REVIEW

File: src/main/java/com/squareup/kotlinpoet/CodeWriter.kt [hunk 1]
```diff
@@ -317,7 +317,7 @@ internal class CodeWriter @JvmOverloads constructor(
     if (o is TypeSpec) {
       o.emit(this, null)
     } else if (o is AnnotationSpec) {
-      o.emit(this, true)
+      o.emit(this, inline = true, asParameter = true)
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/CodeWriter.kt]: Hmm I'm a bit unsure about this behavior as it could affect code in places we don't expect. As we don't have any tests which currently exercise this behavior I'm going to opt for the fix instead of being overly defensive. We may need to revisit this should a use-case come up.

Comment (Egorand) [inline src/main/java/com/squareup/kotlinpoet/CodeWriter.kt]: Agreed, it's too generic here, however I didn't find a better option and was just relying on tests.
