### PR TITLE
Enhance import generation for extension members in KDocs

### LINKED ISSUE #2189: Imports are not resolved for extension properties used via %M in KDocs
**Describe the bug**
When defining a `MemberName` with `isExtension = true`, if the only usage is in a KDoc via `%M`, the FQ name will get embedded rather than the simple name. If another usage of the member exists in the file, the simple name will get embedded.

**To Reproduce**

This works as expected:

```kotlin
fun main() {
  val dpFactoryFunction =
    MemberName(packageName = "androidx.compose.ui.unit", simpleName = "dp", isExtension = true)

  val properties =
    listOf(
      PropertySpec.builder("bar", com.squareup.kotlinpoet.INT)
        .initializer("42")
        .addKdoc("`42.%M`", dpFactoryFunction)
        .build(),
      PropertySpec.builder("baz", com.squareup.kotlinpoet.FLOAT)
        .initializer("42.%M.value", dpFactoryFunction)
        .build(),
    )

  val file = FileSpec.builder("foo", "Foo").addProperties(properties).build()
  file.writeTo(System.out)
}
```

Generating the following (correct) code:

```kotlin
package foo

import androidx.compose.ui.unit.dp
import kotlin.Float
import kotlin.Int

/**
 * `42.dp`
 */
public val bar: Int = 42

public val baz: Float = 42.dp.value
```

Removing the `baz` property results in the FQ name being used (incorrectly) in the remaining `bar` property's KDoc:

```kotlin
package foo

import kotlin.Int

/**
 * `42.androidx.compose.ui.unit.dp`
 */
public val bar: Int = 42
```

I also tried manually calling `.addImport` with the `dpFactoryFunction` on the `FileSpec.Builder`, but the resolution behavior does not change.

**Expected behavior**
Unclear to me if the usage of an extension via `%M` _only_ in imports should trigger the generation of an import (I personally do prefer it that way), or if it should effectively do what `%N` does and just output `dp` in this case without being concerned about imports.

I think it could be argued that the right thing to use here is `%N` and not `%M`, but it seems unexpected to me that I get the intended behavior if another property exists in the file that triggers the import.

**Additional context**
Currently the workaround of just switching from `%M` to `%N` does work, but I had some code-paths that were being shared for KDoc value generation and actual code generation that worked nicely until I hit this edge-case.

### PR DESCRIPTION
**Pull request by RaoPrashanth**
# Fix: Generate imports for extension members used via %M in KDocs

Refactored the condition to prioritize extension members for import generation regardless of the KDoc context:
- Extension members are now always marked as importable, ensuring they can be referenced by simple name and have proper clickable links in generated documentation
- Non-extension members in KDocs continue to use the existing behavior (not marked as importable)

**Fixes #2189**

- [x] `docs/changelog.md` has been updated if applicable.
  - Changes not visible to library consumers, such as build script, documentation, or test code updates, don't need to
    be added to the changelog.
- [x] [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1) signed.

### CODE REVIEW

**Review by JakeWharton — APPROVED** [review]
Tests seem a bit overkill/redundant but that's fine. Looks good otherwise.

File: kotlinpoet/src/jvmTest/kotlin/com/squareup/kotlinpoet/MemberNameTest.kt [hunk 1]
```diff
@@ -714,4 +714,176 @@ class MemberNameTest {
...
+  }
+
+  // https://github.com/square/kotlinpoet/issues/2189
+  @Test
+  fun `non-extension member used only in kdoc generates import and linkable`() {
+    val createTaco = MemberName("com.squareup.tacos", "createTaco")
+
+    val function =
+      FunSpec.builder("main")
+        .addKdoc("Creates a taco using [%M]\n", createTaco)
```
Comment (Egorand) [inline kotlinpoet/src/jvmTest/kotlin/com/squareup/kotlinpoet/MemberNameTest.kt]: I wonder if it'd be useful to always wrap %T or %M members appearing in KDoc with [] so they're automatically clickable? We can consider this as a follow-up.
