### PR TITLE
Fix importing annotated TypeName

### LINKED ISSUE #346: Annotated TypeName not imported when used as type argument in ParameterizedTypeName
```kotlin
@Test fun typeArgumentNotImported() {
  val file = FileSpec.builder("com.squareup.tacos", "Taco")
      .addFunction(FunSpec.builder("foo")
          .addParameter("a", ParameterizedTypeName.get(
              rawType = List::class.asTypeName(),
              typeArguments = *arrayOf(Int::class.asTypeName()
                  .annotated(AnnotationSpec.builder(JvmSuppressWildcards::class)
                      .build()))
          ))
          .build())
      .build()
  assertThat(file.toString()).isEqualTo("""
    |package com.squareup.tacos
    |
    |import kotlin.Int
    |import kotlin.collections.List
    |import kotlin.jvm.JvmSuppressWildcards
    |
    |fun foo(a: List<@JvmSuppressWildcards kotlin.Int>) {
    |}
    |""".trimMargin())
}
```

Without the annotation that would emit `List<Int>`

### PR DESCRIPTION
**Pull request by Egorand**
Fixes #346

### CODE REVIEW

File: src/test/java/com/squareup/kotlinpoet/KotlinPoetTest.kt [hunk 1]
```diff
@@ -650,4 +650,28 @@ class KotlinPoetTest {
       |class Taco(@JvmField val foo: String)
       |""".trimMargin())
   }
+
+  // https://github.com/square/kotlinpoet/issues/346
+  @Test fun typeArgumentNotImported() {
```
Comment (JakeWharton) [inline src/test/java/com/squareup/kotlinpoet/KotlinPoetTest.kt]: Name seems backwards

File: src/main/java/com/squareup/kotlinpoet/CodeWriter.kt [hunk 2]
```diff
@@ -326,7 +326,7 @@ internal class CodeWriter constructor(
       nameResolved = resolved != null
 
       // We don't care about nullability here, as it's irrelevant for imports.
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/CodeWriter.kt]: Update comment to match
