### PR TITLE
Remove superfluous newline

### LINKED ISSUE #1725: Regression in KDoc generation whitespace
I think as a result of #1637, we unconditionally add a newline after the docs even if no tags are going to be emitted.

This is causing a failure in SQL Delight here https://github.com/cashapp/sqldelight/pull/4823

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #1725 

It's pretty amazing this wasn't tested anywhere (even implicitly).

### CODE REVIEW

File: kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/TypeSpec.kt [hunk 1]
```diff
@@ -390,12 +390,16 @@ public class TypeSpec private constructor(
...
+        }
+        if (primaryConstructor.kdoc.isNotEmpty()) {
+          add("@constructor %L", primaryConstructor.kdoc.ensureEndsWithNewLine())
+        }
+        parametersWithKdoc.forEach { parameter ->
+          add("@param %L %L", parameter.name, parameter.kdoc.ensureEndsWithNewLine())
+        }
       }
       build()
     }
```
Comment (Egorand) [inline kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/TypeSpec.kt:405]: I wanted to avoid a thousand `if`s so did this, see if you like it better (sadly can't add as a suggestion):

```kotlin
val constructorKdoc = buildCodeBlock {
  if (primaryConstructor.kdoc.isNotEmpty()) {
    add("@constructor %L", primaryConstructor.kdoc.ensureEndsWithNewLine())
  }
  parametersWithKdoc.forEach { parameter ->
    add("@param %L %L", parameter.name, parameter.kdoc.ensureEndsWithNewLine())
  }
}
return listOf(kdoc.ensureEndsWithNewLine(), constructorKdoc)
  .filter(CodeBlock::isNotEmpty)
  .joinToCode(separator = "\n")
```

**Review by Egorand — APPROVED** [review]

File: kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/TypeSpec.kt (hunk 1 above)
Comment (JakeWharton) [reply kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/TypeSpec.kt:405]: Ship it

Comment (JakeWharton) [reply kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/TypeSpec.kt]: Ended up pulling even more into this. Because the code above also had conditionals and functional list operations. Combined everything as best I could with minimal conditional logic.
