### PR TITLE
KSP typealias fixes

### LINKED ISSUE #1945: KSAnnotation.toAnnotationSpec() fails if the KSAnnotation is a typealias to another Annotation
**Describe the bug**

Consider following scenario:
```kotlin
annotation class SomeAnnotation
typealias SomeOtherAnnotation = SomeAnnotation

@SomeOtherAnnotation
fun doSomething() {
}
```
Calling `KSAnnotation.toAnnotationSpec()` on the `doSomething` function annotations, KSP will throw:

```
e: java.lang.ClassCastException: class com.google.devtools.ksp.impl.symbol.kotlin.KSTypeAliasImpl cannot be cast to class com.google.devtools.ksp.symbol.KSClassDeclaration (com.google.devtools.ksp.impl.symbol.kotlin.KSTypeAliasImpl and com.google.devtools.ksp.symbol.KSClassDeclaration are in unnamed module of loader 'app')
	at com.squareup.kotlinpoet.ksp.AnnotationsKt.toAnnotationSpec(Annotations.kt:48)
	at com.squareup.kotlinpoet.ksp.AnnotationsKt.toAnnotationSpec$default(Annotations.kt:35)...
```

**Expected behavior**
- I would expect this to work, without errors.
- `KSAnnotation.toAnnotationSpec()` should return resolved annotation

**Additional context**
https://github.com/square/kotlinpoet/blob/79ec8a42447a94db5b738fa303c8d433ad459bcb/interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt#L48

This seems like it should be a safe cast to KSClassDeclaration

### PR DESCRIPTION
**Pull request by ZacSweers**
See changelog!

Resolves #1945

### CODE REVIEW

File: interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt [hunk 1]
```diff
@@ -21,31 +21,28 @@ import com.google.devtools.ksp.symbol.KSAnnotation
...
-        AnnotationSpec.builder(className.parameterizedBy(typeArgs))
-      }
-    }
+  val typeName = annotationType.resolve().toTypeName()
+
+  val builder = if (typeName is ClassName) {
+    AnnotationSpec.builder(typeName)
+  } else {
+    AnnotationSpec.builder(typeName as ParameterizedTypeName)
+  }
```
Comment (Egorand) [inline interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt:42]: If `typeName` is neither `ClassName` nor `ParameterizedTypeName` - we crash?

File: docs/changelog.md [hunk 2]
```diff
@@ -4,6 +4,10 @@ Change Log
 ## Unreleased
 
 * Fix: Enum classes that only have an init block now also generate the required semicolon (#1952)
+* Fix: Preserve typealiases in `KSAnnotation.toAnnotationSpec()`. (#1945)
```
Comment (Egorand) [inline docs/changelog.md:7]: nit:

```suggestion
* Fix: Preserve typealiases in `KSAnnotation.toAnnotationSpec()`. (#1956)
```

**Review by Egorand — APPROVED** [review]

File: interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt (hunk 1 above)
Comment (ZacSweers) [reply interop/ksp/src/main/kotlin/com/squareup/kotlinpoet/ksp/Annotations.kt:42]: Yes but it should be impossible for that to happen here

File: docs/changelog.md (hunk 2 above)
Comment (ZacSweers) [reply docs/changelog.md:7]: This one actually linked the issue, so we link issues or fixes?

Comment (Egorand) [reply docs/changelog.md:7]: I link fixes when compiling the changelog for a release, since fixes contain actually diffs. Does it make more sense to link issues?

Comment (ZacSweers) [reply docs/changelog.md:7]: Up to you! I always just pick whichever one was contributed externally for their visibility as a default, but no strong feelings

Comment (ZacSweers) [reply docs/changelog.md:7]: Gonna roll with this
