### PR TITLE
Omit implicit modifiers on `FileSpec.scriptBuilder`

### LINKED ISSUE #1620: Broken functions in scripts
**Describe the bug**
Functions in generated script (via `FileSpec.scriptBuilder`) get `public` modifier which is prohibited for local functions in Kotlin scripts.

**To Reproduce**
```kotlin
fun main() {
    val funSpec = FunSpec.builder("foo")
        .apply { returns(UNIT) }
        .build()
    val fileSpec = FileSpec.scriptBuilder("dummy")
        .apply { addFunction(funSpec) }
        .build()

    println(fileSpec.toString())
    
    // public fun foo() {
    //}

    //ERROR: Modifier 'public' is not applicable to 'local function'
}
```

**Expected behavior**
- don't add implicit `public` modifier to functions in script body
OR
- allow to switch off `explicit API` compatibility mode

**Additional context**
KotlinPoet 1.14.2

### PR DESCRIPTION
**Pull request by psymoon**
Closes #1620

### CODE REVIEW

File: kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/CodeWriter.kt [hunk 1]
```diff
@@ -393,15 +394,15 @@ internal class CodeWriter constructor(
...
+  private fun emitLiteral(o: Any?, isConstantContext: Boolean, omitImplicitModifiers: Boolean) {
     when (o) {
       is TypeSpec -> o.emit(this, null)
       is AnnotationSpec -> o.emit(this, inline = true, asParameter = isConstantContext)
       is PropertySpec -> o.emit(this, emptySet())
       is FunSpec -> o.emit(
         codeWriter = this,
         enclosingName = null,
-        implicitModifiers = setOf(KModifier.PUBLIC),
+        implicitModifiers = setOfNotNull(KModifier.PUBLIC.takeUnless { omitImplicitModifiers }),
```
Comment (JakeWharton) [inline kotlinpoet/src/commonMain/kotlin/com/squareup/kotlinpoet/CodeWriter.kt:405]: Would prefer a simple if/else here
```suggestion
        implicitModifiers = if (omitImplicitModifiers) emptySet() else setOf(KModifier.PUBLIC),
```

**Review by JakeWharton — APPROVED** [review]

**Review by Egorand — APPROVED** [review]
Dope, thank you!
