### PR TITLE
Replace Java keyword checks with Kotlin.

### LINKED ISSUE #164: Check for Kotlin keywords.
FunSpec.builder("void") fails. FunSpec.builder("fun") will generate.
I don't know of a Kotlin version of `SourceVersion.isName`.

Since it'll generate code that won't compile, I don't know if this check adds much value, anyway.

### PR DESCRIPTION
**Pull request by NightlyNexus**
Closes #164, as far as I can tell.

### CODE REVIEW

File: src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 1]
```diff
@@ -113,3 +114,47 @@ internal fun stringLiteralWithQuotes(value: String): String {
...
   }
 }
+
+internal fun isKeyword(name: String): Boolean {
+  return KEYWORDS.contains(name)
+}
+
+internal fun isName(name: String): Boolean {
+  return NAME_REGEX.split(name, 0).toTypedArray()
+      .none { !isIdentifier(it) || isKeyword(name) }
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: I want to drop the Java check altogether.

Comment (NightlyNexus) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: Ah, right.
i'll give look at it and ask more here.

**Comment by NightlyNexus** [comment]
am i going down the right path here for replacing isIdentifier?
do i need to find the list of illegal characters and hardcode them in here?
```kotlin
internal fun isIdentifier(name: String): Boolean {
  val first = name.codePointAt(0)
  if (first !in '\u001f'.toInt()..'\u007f'.toInt() || first == '.'.toInt() // TODO: illegal characters
      || first in '0'.toInt()..'9'.toInt()) {
    return false
  }
  var i = if (first >= 0x010000) 2 else 1
  while (i < name.length) {
    val part = name.codePointAt(i)
    if (first !in '\u001f'.toInt()..'\u007f'.toInt() || first == '.'.toInt()) {
      return false
    }
    i += if (part >= 0x010000) 2 else 1
  }
  return true
}
```

**Comment by JakeWharton** [comment]
Honestly I was just thinking we guard against all the keywords for now and that'd be it. I don't know enough about Kotlin's restrictions on naming, but that looks alright.

**Comment by NightlyNexus** [comment]
Oh, gotcha. and leave [this](https://github.com/square/kotlinpoet/blob/9b44af2ba31b4fbda76cd23d68fda13e4b53be5d/src/main/java/com/squareup/kotlinpoet/CodeWriter.kt#L28) for now?

I also don't know the restrictions.
But, a quick look at https://jetbrains.github.io/kotlin-spec/ makes it look easy enough.
I'm going to try squeezing in the replacement into this change in a bit.

**Comment by JakeWharton** [comment]
Ideally that one also changes to be Kotlin-specific eventually.

File: src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 2]
```diff
@@ -113,3 +113,60 @@ internal fun stringLiteralWithQuotes(value: String): String {
     return result.toString()
   }
 }
+
+internal fun isIdentifier(name: String): Boolean {
+  return IDENTIFIER_NAME_REGEX.matches(name) || IDENTIFIER_NAME_WITH_BACKTICKS_REGEX.matches(name)
```
Comment (NightlyNexus) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: oh, actually could merge the regexes.

**Comment by NightlyNexus** [comment]
added some more tests. sorry for that notification spam.

File: src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 3]
```diff
@@ -113,3 +113,58 @@ internal fun stringLiteralWithQuotes(value: String): String {
...
+    "object",
+    "if",
+    "try",
+    "else",
+    "while",
+    "do",
+    "when",
+    "interface",
+    "typeof"
+)
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: What about `public` and the like?

File: src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 4]
```diff
@@ -113,3 +113,58 @@ internal fun stringLiteralWithQuotes(value: String): String {
...
+internal fun isIdentifier(name: String): Boolean {
+  return IDENTIFIER_REGEX.matches(name)
+}
+
+internal fun isKeyword(name: String): Boolean {
+  return KEYWORDS.contains(name)
+}
+
+internal fun isName(name: String): Boolean {
+  return NAME_REGEX.split(name, 0).toTypedArray().none { isKeyword(name) }
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: There's an overload of `split` that takes a `CharSequence` instead of a `Regex`. Can we just use that with `"."`?

File: src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 5]
```diff
@@ -113,3 +113,58 @@ internal fun stringLiteralWithQuotes(value: String): String {
...
+}
+
+private val NAME_REGEX = "\\.".toRegex()
+private val IDENTIFIER_REGEX
+    = ("((\\p{gc=Lu}+|\\p{gc=Ll}+|\\p{gc=Lt}+|\\p{gc=Lm}+|\\p{gc=Lo}+|\\p{gc=Nl}+)+" +
+    "\\d*" +
+    "\\p{gc=Lu}*\\p{gc=Ll}*\\p{gc=Lt}*\\p{gc=Lm}*\\p{gc=Lo}*\\p{gc=Nl}*)" +
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: This is intense! Is there an explanation about where it came from? Can we accomplish this with imperative code that would be more readable (and maintainable)?

File: src/main/java/com/squareup/kotlinpoet/Util.kt (hunk 3 above)
Comment (NightlyNexus) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: `public` is allowed. like `fun public() {}`

File: src/main/java/com/squareup/kotlinpoet/Util.kt (hunk 4 above)
Comment (NightlyNexus) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: yep!

File: src/main/java/com/squareup/kotlinpoet/Util.kt (hunk 5 above)
Comment (NightlyNexus) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: https://jetbrains.github.io/kotlin-spec/#_lexical_grammar
identifier-start (line 131) and identifier-part (132 and 133).

Yeah, it's too crazy. I'll look at it again and see if I can think of anything.

File: src/main/java/com/squareup/kotlinpoet/Util.kt (hunk 3 above)
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: Huh. Cool.

File: src/main/java/com/squareup/kotlinpoet/Util.kt (hunk 5 above)
Comment (NightlyNexus) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: I'm not sure what to do here.
We could duplicate Character.isLetter as a helper and use a loop.
Any ideas?
I could also revert this and only replace `isKeyword` and `isName` until we think of something sane.

**Comment by swankjesse** [comment]
Thanks!
