### PR TITLE
Throw IllegalArgumentException when trying to escape illegal characters

### LINKED ISSUE #701: Improve name escaping logic
As demonstrated by #698, we incorrectly assume that any characters escaped by backticks form a correct name. This is not true, e.g. this will not compile:
```kotlin
class `My.Class` // dots are illegal, even after escaping
```
We should fix name validation logic and throw if the name contains characters that can't be escaped.

### PR DESCRIPTION
**Pull request by Wasabi375**
fixes #701

### CODE REVIEW

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 1]
```diff
@@ -218,3 +225,6 @@ private val KEYWORDS = setOf(
     "interface",
     "typeof"
 )
+
+// https://github.com/JetBrains/kotlin/blob/master/compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/checkers/JvmSimpleNameBacktickChecker.kt
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt]: Nice!

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 2]
```diff
@@ -295,14 +295,21 @@ class TypeSpec private constructor(
...
 
       result[property.name] = property.fromPrimaryConstructorParameter(parameter)
     }
     return result
   }
 
+  /**
+   * Returns `true if the property can be declared inline as a constructor parameter
+   */
+  private fun isPropertyInitializerConstructorParameter(property: PropertySpec, parameter: ParameterSpec): Boolean {
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: nit: Feels like these lines are too long, I'm surprised that Spotless didn't catch it.

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 3]
```diff
@@ -15,6 +15,7 @@
  */
 package com.squareup.kotlinpoet
 
+import java.lang.IllegalArgumentException
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt]: I think we should throw `kotlin.IllegalArgumentException` instead. Just removing the import should do the job.

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 4]
```diff
@@ -151,7 +152,13 @@ internal fun String.escapeIfKeyword() = if (isKeyword) "`$this`" else this
 internal fun String.escapeIfNotJavaIdentifier() =
   if (!Character.isJavaIdentifierStart(first()) || drop(1).any { !Character.isJavaIdentifierPart(it) }) "`$this`" else this
 
-internal fun String.escapeIfNecessary() = escapeIfNotJavaIdentifier().escapeIfKeyword()
+internal fun String.escapeIfNecessary() = escapeIfNotJavaIdentifier().escapeIfKeyword().failIfEscapeInvalid()
+
+internal fun String.failIfEscapeInvalid() =
+  if (any { it in illegalCharactersToEscape })
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt]: nit: Let's use `{}` with this if-else block.

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 5]
```diff
@@ -218,3 +225,6 @@ private val KEYWORDS = setOf(
     "interface",
     "typeof"
 )
+
+// https://github.com/JetBrains/kotlin/blob/master/compiler/frontend.java/src/org/jetbrains/kotlin/resolve/jvm/checkers/JvmSimpleNameBacktickChecker.kt
+private val illegalCharactersToEscape = setOf('.', ';', '[', ']', '/', '<', '>', ':', '\\')
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt]: nit: Should the name be in UPPER_SNAKE_CASE, since it's a constant?

File: kotlinpoet/src/test/java/com/squareup/kotlinpoet/KotlinPoetTest.kt [hunk 6]
```diff
@@ -884,4 +884,13 @@ class KotlinPoetTest {
       |}
       |""".trimMargin())
   }
+
+  // https://github.com/square/kotlinpoet/issues/701
+  @Test fun noIllegalCharacterInIdentifier() {
+    assertThrows<java.lang.IllegalArgumentException> {
```
Comment (Egorand) [inline kotlinpoet/src/test/java/com/squareup/kotlinpoet/KotlinPoetTest.kt]: nit: Remove `java.lang.`.

Comment (Wasabi375) [reply kotlinpoet/src/test/java/com/squareup/kotlinpoet/KotlinPoetTest.kt]: Not sure how `java.lang` got in there in the first place. Same above

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt (hunk 4 above)
Comment (Wasabi375) [reply kotlinpoet/src/main/java/com/squareup/kotlinpoet/Util.kt]: I changed it to a require. After adding a few braces intellij suggested it and I think it's better this way.

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt (hunk 2 above)
Comment (Wasabi375) [reply kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt]: I guess it's just short enough. Should be better now though

**Comment by Wasabi375** [comment]
If the CLA is the same as for Moshi I signed it.
