### PR TITLE
Disallow enum constants and properties called "name" and "ordinal"

### LINKED ISSUE #1183: name and ordinal enum constant names generates non-compiling code
```kotlin
    val byeNat = TypeSpec.enumBuilder("ByeNat")
      .addEnumConstant("name")
      .addEnumConstant("ordinal")
      .build()
```
This will fail because Kotlin enums already have an `name` and an `ordinal` fields.

### PR DESCRIPTION
**Pull request by Egorand**
Since it's a well-known limitation, perhaps it does make sense to validate it in the library.

Fixes #1183

### CODE REVIEW

File: kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeSpecTest.kt [hunk 1]
```diff
@@ -5015,6 +5016,42 @@ class TypeSpecTest {
     )
   }
 
+  // https://github.com/square/kotlinpoet/issues/1183
+  @Test fun `forbidden enum constant names`() {
+    var exception = assertFailsWith<IllegalArgumentException> {
+      TypeSpec.enumBuilder("Topping")
+        .addEnumConstant("name")
+    }
```
Comment (oldergod) [inline kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeSpecTest.kt:5024]: Interesting, the validation doesn't happen on `build` ?

**Review by oldergod — COMMENTED** [review]
I would use the _final supertype member_ in both cases, I think it's the clearest.

**Review by oldergod — APPROVED** [review]

File: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt [hunk 2]
```diff
@@ -650,6 +650,9 @@ public class TypeSpec private constructor(
       name: String,
       typeSpec: TypeSpec = anonymousClassBuilder().build()
     ): Builder = apply {
+      require(name != "name" && name != "ordinal") {
+        "constant with name \"$name\" conflicts with a property with the same name"
```
Comment (Egorand) [inline kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeSpec.kt:654]:
```suggestion
        "constant with name \"$name\" conflicts with a supertype member with the same name"
```
