### PR TITLE
Escape packageName components in FileSpec which are also Kotlin keywords

### LINKED ISSUE #247: Check packageName components for keywords
The following will generate an invalid package name because of the `in` keyword in one of its components:

```kotlin
@Test fun keywordInPackageName() {
  val source = FileSpec.builder("com.squareup.in", "California")
      .build()
  assertThat(source.toString()).isEqualTo("""
      |package com.squareup.in
      |
      |""".trimMargin())
}
```

Would it be advisable to automatically adjust the emitted code to include the grave accents around keywords (i.e. ``` package com.squareup.`in` ```)? If not, should we extend the [existing sanity checks in FileSpec.Builder](https://github.com/square/kotlinpoet/blob/4b0e6e2b714bfbee559498c4f14db2c4e6605a41/src/main/java/com/squareup/kotlinpoet/FileSpec.kt#L177) to validate the `packageName` components at initialization time as well, and fail quickly on reserved keywords?

### PR DESCRIPTION
**Pull request by mannodermaus**
Fixes #247

### CODE REVIEW

**Comment by mannodermaus** [comment]
Let me know if `escapeIfKeyword(String)` should be an extension property instead, I went with my gut feeling, looking at the remaining code in `Util.kt` for reference.

File: src/main/java/com/squareup/kotlinpoet/FileSpec.kt [hunk 1]
```diff
@@ -165,8 +165,10 @@ class FileSpec private constructor(builder: FileSpec.Builder) {
   }
 
   class Builder internal constructor(
-      internal val packageName: String,
+      packageName: String,
       internal val name: String) {
+    internal val packageName = packageName.split('.')
+        .joinToString(".") { escapeIfKeyword(it) }
```
Comment (JakeWharton) [inline src/main/java/com/squareup/kotlinpoet/FileSpec.kt]: I think we only want to do this inside of `writeTo`, since currently we'd expose this escaped version which might break someone using it for something else.

**Comment by mannodermaus** [comment]
Deferred the actual replacement to `FileSpec#emit()`.

File: src/main/java/com/squareup/kotlinpoet/Util.kt [hunk 2]
```diff
@@ -133,6 +133,8 @@ internal fun stringLiteralWithQuotes(value: String): String {
   }
 }
 
+internal fun escapeIfKeyword(value: String): String = if (value.isKeyword) "`$value`" else value
```
Comment (Egorand) [inline src/main/java/com/squareup/kotlinpoet/Util.kt]: nit: return type can be omitted

Comment (mannodermaus) [reply src/main/java/com/squareup/kotlinpoet/Util.kt]: True. Updated!
